### ISSUE TITLE
Section 1: Introduction [Owner: Harsha with Tanvi, Tanuj]

### ISSUE THREAD

**Issue by tanvipeopleplusai** [PeoplePlusAI/adbhut-india#16]
## subtasks managed by section owner

- [x] Initial draft for v.1 being written
- [x] Ready for peer review
- [x] Peer review in progress
- [ ] Feedback has been incorporated
- [ ] Ready for integration in to v.1
