### ISSUE TITLE
Section 5: Guiding Policy [Owner: Tanuj & Harsha]

### ISSUE THREAD

**Issue by tanvipeopleplusai** [PeoplePlusAI/adbhut-india#20]
## subtasks managed by section owner

- [x] Initial draft for v.1 being written
- [x] Ready for peer review
- [x] Peer review in progress
- [ ] Feedback has been incorporated
- [ ] Ready for integration in to v.1
